# =============================
# Stage 0: Base With Bun & Turbo
# =============================
FROM oven/bun:1.2.22 AS base

RUN bun add -g turbo

# =============================
# Stage 1: Builder (Pruned Repo)
# =============================
FROM base AS builder
WORKDIR /app

# Copy entire monorepo into the builder image
COPY . .

# Ensure bun.lock is generated by running bun install
RUN bun install

# Prune for API workspace (Monorepo → Pruned)
RUN turbo prune @midday/api --docker

# Move into pruned workspace
WORKDIR /app/out/full

# Install deps for build
RUN bun install

# Build engine inside the pruned workspace
RUN cd apps/engine && bun run build

# =============================
# Stage 2: Installer (Production)
# =============================
FROM base AS installer
WORKDIR /app

# Install production dependencies from pruned output
COPY --from=builder /app/out/json/ .
RUN bun install

# Copy source code from pruned output
COPY --from=builder /app/out/full/ .

# Copy built engine dist from pruned output
COPY --from=builder /app/out/full/apps/engine/dist ./apps/engine/dist


# =============================
# Stage 3: Runner
# =============================
FROM installer AS runner

WORKDIR /app/apps/api

ENV NODE_ENV=production
EXPOSE 8080

CMD ["bun", "run", "src/index.ts"]
